//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WezwijPomoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public string kod_pocztowy { get; set; }
        public string miejscowosc { get; set; }
        public string wojewodztwo { get; set; }
        public string powiat { get; set; }
        public int id_adresu { get; set; }
    }
}
