//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WezwijPomoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instytucja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instytucja()
        {
            this.Zgloszenie = new HashSet<Zgloszenie>();
            this.Zgloszenie1 = new HashSet<Zgloszenie>();
            this.Uzytkownik = new HashSet<Uzytkownik>();
        }
    
        public int id_instytucji { get; set; }
        public string nazwa_instytucji { get; set; }
        public string kod_pocztowy { get; set; }
        public Nullable<int> typ_instytucji { get; set; }
        public string wojewodztwo { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgloszenie> Zgloszenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgloszenie> Zgloszenie1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Uzytkownik> Uzytkownik { get; set; }
    }
}
