//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WezwijPomoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int id_ticketu { get; set; }
        public string nr_telefonu { get; set; }
        public Nullable<System.DateTime> data_zgloszenia { get; set; }
        public string kod_sms { get; set; }
        public string ip { get; set; }
    }
}
