//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WezwijPomoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownik()
        {
            this.Zgloszenie = new HashSet<Zgloszenie>();
            this.Zgloszenie1 = new HashSet<Zgloszenie>();
        }
    
        public string login { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string numer_telefonu { get; set; }
        public string haslo { get; set; }
        public string mail { get; set; }
        public int rola { get; set; }
        public int id_instytucji { get; set; }
        public int id_uzytkownika { get; set; }
        public int status { get; set; }
    
        public virtual Instytucja Instytucja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgloszenie> Zgloszenie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zgloszenie> Zgloszenie1 { get; set; }
    }
}
