//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WezwijPomoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgloszenie
    {
        public int id_zgloszenia { get; set; }
        public string zakres_wsparcia { get; set; }
        public int priorytet { get; set; }
        public string kod_pocztowy { get; set; }
        public string adres_zgloszenia { get; set; }
        public int id_instytucji_przyjm { get; set; }
        public int id_instytucji_zgl { get; set; }
        public int id_statusu { get; set; }
        public System.DateTime data_rozpoczecia { get; set; }
        public System.DateTime data_wygenerowania { get; set; }
        public int id_osoby_do_kontaktu { get; set; }
        public int id_uzytkownika_zgl { get; set; }
        public Nullable<int> id_uzytkownika_przyjm { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Instytucja Instytucja { get; set; }
        public virtual Instytucja Instytucja1 { get; set; }
        public virtual Osoba Osoba { get; set; }
        public virtual Status Status { get; set; }
        public virtual Uzytkownik Uzytkownik { get; set; }
        public virtual Uzytkownik Uzytkownik1 { get; set; }
    }
}
