//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WezwijPomoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zgloszenie
    {
        public int id_zgloszenia { get; set; }
        public string pesel { get; set; }
        public string imie { get; set; }
        public string nr_telefonu { get; set; }
        public string kategoria_pomocy { get; set; }
        public string kod_pocztowy { get; set; }
        public string adres_zgloszenia { get; set; }
        public int id_batalionu { get; set; }
        public int id_instytucji { get; set; }
        public int id_statusu { get; set; }
    
        public virtual Adres Adres { get; set; }
        public virtual Batalion Batalion { get; set; }
        public virtual Instytucja Instytucja { get; set; }
        public virtual Status Status { get; set; }
    }
}
